### ISSUE TITLE
Issue#71 from integration_google also applies to this

### ISSUE THREAD

**Issue by ClaraCrazy** [julien-nc/integration_onedrive#24]
https://github.com/nextcloud/integration_google/issues/71

just so you have it on your screen and dont forget it.

Would love to hear an ETA for a fix if possible

**Comment by eneiluj** [comment]
Sorry for the ultra late response.

It was fixed in v1.1.1 which was released before your comment. Did you have a chance to try it?

**Comment by julien-nc** [comment]
Feel free to reopen if needed.
